spring.application.name=back_API_ERP_Supermercado

server.port=3005


spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

# Cambiar el nombre de la BD en la .env
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}

#Cambiar el usuario de tu base de datos, password
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver



