spring.application.name=back_API_ERP_Supermercado

server.port=3005

# jwt.secret=ejemplo
# jwt.expiration=86400000

spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres

# Cambiar el descripcion de la BD en la .env
spring.datasource.url=jdbc:postgresql://localhost:5432/supermercadoprueba
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

#configurar del JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-plataform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true

